{pkgs ? import <nixpkgs> {}}:
pkgs.mkShell {
  # nativeBuildInputs is usually what you want -- tools you need to run
  nativeBuildInputs = with pkgs.buildPackages; [
    gtk3
    util-linux
    libselinux
    libsepol
    libthai
    libdatrie
    xorg.libXdmcp
    lerc
    libxkbcommon
    pcre2
    pkg-config
    cmake
    mpv
    libass
    mimalloc
    ffmpeg
    libplacebo
    libunwind
    shaderc
    vulkan-loader
    lcms
    libdovi
    libdvdnav
    libdvdread
    mujs
    libbluray
    lua
    rubberband
    SDL2
    libuchardet
    zimg
    alsa-lib
    openal
    pipewire
    pulseaudio
    libcaca
    libdrm
    mesa
    xorg.libXScrnSaver
    xorg.libXpresent
    xorg.libXv
    nv-codec-headers-12
    libva
    libvdpau
  ];
}
